### PR TITLE
fix: esm resolving issue

### PR DESCRIPTION
**Pull request by Songkeys**
> Error [ERR_REQUIRE_ESM]: require() of ES Module ... not supported.
pws.umd.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename pws.umd.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /Users/songkeys/GitHub/Crossbell-Box/indexer-v1/node_modules/pws/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

### CODE REVIEW

**Comment by porsager** [comment]
How and where are you importing / requiring `pws` which returns this error?

**Comment by Songkeys** [comment]
I am using this in the nestjs framework specifically. they are using typescript + webpack for the build.

I think the issue is the `"default"` field in conditional exports - it could either be cjs or mjs. If the file format isn't specified, it will follow the `"type"` field in package.json, which is `"module"` in this case.

Another solution is to use `"require"` instead of `"default"` for cjs entries.

see: https://nodejs.org/api/packages.html#conditional-exports

**Comment by porsager** [comment]
This PR breaks all thy way I'm using pws, so we should probably find a less invasive way to support nestjs / webpack.

**Comment by porsager** [comment]
Sorry for getting back to this so late - would you mind trying to see if this is fixed for you in the just release v7 ?

**Pull request closed without merging**
